config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.local?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      resources :connected_accounts
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: ("users/omniauth_callbacks" if defined? OmniAuth),
      registrations: "users/registrations",
      sessions: "users/sessions"
    }.compact
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get "session/otp", to: "sessions#otp"
  end
  resources :after_signup

  resources :announcements, only: [:index, :show]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
      delete :delete_photo_attachment
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts do
      member do
        post :resend
      end
    end
  end
  resources :account_invitations

  # Payments
  resource :billing_address
  namespace :payment_methods do
    resource :stripe, controller: :stripe, only: [:show]
  end
  resources :payment_methods
  namespace :subscriptions do
    resource :billing_address
    namespace :stripe do
      resource :trial, only: [:show]
    end
  end
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    resource :upcoming, module: :subscriptions

    collection do
      patch :billing_settings
    end

    scope module: :subscriptions do
      resource :stripe, controller: :stripe, only: [:show]
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  resources :agreements, module: :users
  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :careers
    get :guides
    get :terms
    get :privacy
    get :pricing
    get :sign_up_entry
    get :guide_onboarding
    get :become_a_guide
    post "add_email_contact", to: "add_email_contact"
    post "add_email_guide", to: "add_email_guide"
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
    resources :account_ratings
    get "/map_pins", to: "dashboard#map_pins"
    get "/page_list", to: "dashboard#page_list"
    resources :tours do
      member do
        delete :delete_photo_attachment
      end
    end
    resources :scheduled_tours do
      collection do
        get :availability
      end
    end
    get "/guide_tours/:account_id", to: "tours#guide_tours", as: "guide_tours"
    get "/success", to: "scheduled_tours#stripe_success"
    get "/cancel", to: "scheduled_tours#stripe_cancel"
    get "/scheduled_tour_payment", to: "scheduled_tours#scheduled_tour_payment"
    get "public_profile/:account_id", to: "accounts#public_profile", as: "public_profile"
  end

  resources :schedules

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Public marketing homepage
  root to: "static#index"
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :bigint           not null, primary key
#  active     :boolean          default(FALSE)
#  begin_date :date
#  end_date   :date
#  fri_end    :time
#  fri_start  :time
#  mon_end    :time
#  mon_start  :time
#  name       :string
#  sat_end    :time
#  sat_start  :time
#  sun_end    :time
#  sun_start  :time
#  thu_end    :time
#  thu_start  :time
#  tue_end    :time
#  tue_start  :time
#  wed_end    :time
#  wed_start  :time
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :bigint           not null
#
# Indexes
#
#  index_schedules_on_account_id  (account_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id)
#
class Schedule < ApplicationRecord
  belongs_to :account
  has_one :schedule_availability, dependent: :destroy
  # Broadcast changes in realtime with Hotwire
  after_create_commit -> { broadcast_prepend_later_to :schedules, partial: "schedules/index", locals: {schedule: self} }
  after_update_commit -> { broadcast_replace_later_to self }
  after_destroy_commit -> { broadcast_remove_to :schedules, target: dom_id(self, :index) }
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # Uncomment to enforce Pundit authorization
  # after_action :verify_authorized
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # GET /schedules
  def index
    @pagy, @schedules = pagy(Schedule.where(account_id: current_account.id).sort_by_params(params[:sort], sort_direction))

    # Uncomment to authorize with Pundit
    # authorize @schedules
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new

    # Uncomment to authorize with Pundit
    # authorize @schedule
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.account = current_account
    # Uncomment to authorize with Pundit
    # authorize @schedule

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, status: :see_other, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])

    # Uncomment to authorize with Pundit
    # authorize @schedule
  rescue ActiveRecord::RecordNotFound
    redirect_to schedules_path
  end

  # Only allow a list of trusted parameters through.
  def schedule_params
    params.require(:schedule).permit(:name, :active, :begin_date, :end_date, :mon_start, :mon_end, :tue_start, :tue_end, :wed_start, :wed_end, :thu_start, :thu_end, :fri_start, :fri_end, :sat_start, :sat_end, :sun_start, :sun_end)

    # Uncomment to use Pundit permitted attributes
    # params.require(:schedule).permit(policy(@schedule).permitted_attributes)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
    <div>
      <h2 class="text-base font-semibold leading-7 text-gray-900">Set Your Schedule Availability</h2>
      <p class="mt-1 text-sm leading-6 text-gray-600">This is where you determine what times of the day you can be booked for tours.</p>
    </div>

    <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-4 sm:grid-cols-6 md:col-span-2">
    
      <div class="sm:col-span-full">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>
      
      <div class="sm:col-span-full">
        <label class="relative inline-flex items-center cursor-pointer form-group">
          <%= form.check_box :active, class: "sr-only peer md:px-4" %>
          <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
          <span class="ml-3 text-sm font-medium text-gray-900">Schedule Active?</span>
        </label>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :begin_date, "Start Date", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.date_field :begin_date, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :end_date, "End Date", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.date_field :end_date, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :sun_start, "Sunday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :sun_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :sun_end, "Sunday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :sun_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :mon_start, "Monday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :mon_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :mon_end, "Monday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :mon_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :tue_start, "Tuesday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :tue_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :tue_end, "Tuesday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :tue_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :wed_start, "Wednesday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :wed_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :wed_end, "Wednesday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :wed_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :thu_start, "Thursday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :thu_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :thu_end, "Thursday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :thu_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :fri_start, "Friday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :fri_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :fri_end, "Friday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :fri_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <br/>

      <div class="sm:col-span-2">
        <%= form.label :sat_start, "Saturday Begin", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :sat_start, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="sm:col-span-2">
        <%= form.label :sat_end, "Saturday End", class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.time_field :sat_end, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <%= form.button button_text(form.send(:submit_default_value)), class: "rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>

    <% if form.object.new_record? %>
      <%= link_to t("cancel"), schedules_path, class: "btn btn-white" %>
    <% else %>
      <%= link_to t("cancel"), schedule_path(@schedule), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/schedules/_index.html.erb
<div id="<%= dom_id(schedule, :index) %>">
  <%= turbo_stream_from schedule %>
  <%= render schedule %>
  <%= link_to "View", schedule, class: "btn btn-white" %>
</div>

app/views/schedules/edit.html.erb
<%= content_for :title, t("shared.scaffold.edit.title", model: "Schedule") %>

<div class="container mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Schedules", schedules_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.edit.title", model: "Schedule") %>
    </h1>
    <%= button_to t("delete"), @schedule, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: t("are_you_sure") } } %>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render "form", schedule: @schedule %>
  </div>
</div>

app/views/schedules/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Schedules</h1>
      <p class="mt-2 text-sm text-gray-700">Create or select a schedule and set your availability.</p>
      <%= badge "Only one schedule should be active", class: "bg-yellow-100 text-black-800 text-xs font-medium" %>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to "New Schedule", new_schedule_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0"><%= sortable @schedules, :name, "Name", class: "text-gray-700 mr-1" %></th>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Starting Date</th>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Ending Date</th>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Active?</th>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Edit Availability</th>            
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
          <% if @schedules.any? %>
          <% @schedules.each do |schedule| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= link_to schedule.name, schedule %></td>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= schedule.begin_date || "No Availability Set" %></td>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= schedule.end_date || "No Availability Set" %></td>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= schedule.active%></td>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= link_to "Edit", edit_schedule_path(schedule) %></td>
            </tr>
          <% end %>
          <% else %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">No Schedules Yet</td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
    <% if @pagy.pages > 1 %>
    <div class="my-6 text-center">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/schedules/new.html.erb
<%= content_for :title, t("shared.scaffold.new.title", model: "Schedule") %>

<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Schedules", schedules_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.new.title", model: "Schedule") %>
    </h1>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render "form", schedule: @schedule %>
  </div>
</div>

app/views/schedules/show.html.erb
<%= content_for :title, "Schedules ##{@schedule.id}" %>
<%= turbo_stream_from @schedule %>

<div class="container mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Schedules", schedules_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      Schedule #<%= @schedule.id %>
    </h1>
    <%= link_to t("edit"), edit_schedule_path(@schedule), class: "btn btn-white" %>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render @schedule %>
  </div>
</div>