config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.local?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      resources :connected_accounts
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: ("users/omniauth_callbacks" if defined? OmniAuth),
      registrations: "users/registrations",
      sessions: "users/sessions"
    }.compact
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get "session/otp", to: "sessions#otp"
  end
  resources :after_signup

  resources :announcements, only: [:index, :show]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
      delete :delete_photo_attachment
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts do
      member do
        post :resend
      end
    end
  end
  resources :account_invitations

  # Payments
  resource :billing_address
  namespace :payment_methods do
    resource :stripe, controller: :stripe, only: [:show]
  end
  resources :payment_methods
  namespace :subscriptions do
    resource :billing_address
    namespace :stripe do
      resource :trial, only: [:show]
    end
  end
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    resource :upcoming, module: :subscriptions

    collection do
      patch :billing_settings
    end

    scope module: :subscriptions do
      resource :stripe, controller: :stripe, only: [:show]
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  resources :agreements, module: :users
  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :careers
    get :guides
    get :terms
    get :privacy
    get :pricing
    get :sign_up_entry
    get :guide_onboarding
    get :become_a_guide
    post "add_email_contact", to: "add_email_contact"
    post "add_email_guide", to: "add_email_guide"
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
    resources :account_ratings
    get "/map_pins", to: "dashboard#map_pins"
    get "/page_list", to: "dashboard#page_list"
    resources :tours do
      member do
        delete :delete_photo_attachment
      end
    end
    resources :scheduled_tours do
      collection do
        get :availability
      end
    end
    get "/guide_tours/:account_id", to: "tours#guide_tours", as: "guide_tours"
    get "/success", to: "scheduled_tours#stripe_success"
    get "/cancel", to: "scheduled_tours#stripe_cancel"
    get "/scheduled_tour_payment", to: "scheduled_tours#scheduled_tour_payment"
    get "public_profile/:account_id", to: "accounts#public_profile", as: "public_profile"
  end

  resources :schedules

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Public marketing homepage
  root to: "static#index"
end

app/models/account_rating.rb
# == Schema Information
#
# Table name: account_ratings
#
#  id                :bigint           not null, primary key
#  rating            :float
#  review            :text
#  title             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  source_account_id :bigint           not null
#  target_account_id :bigint           not null
#
# Indexes
#
#  index_account_ratings_on_source_account_id  (source_account_id)
#  index_account_ratings_on_target_account_id  (target_account_id)
#
# Foreign Keys
#
#  fk_rails_...  (source_account_id => accounts.id)
#  fk_rails_...  (target_account_id => accounts.id)
#
class AccountRating < ApplicationRecord
  enum rating: {one_star_count: 1.0, two_star_count: 2.0, three_star_count: 3.0, four_star_count: 4.0, five_star_count: 5.0}
  belongs_to :target_account, class_name: "Account"
  belongs_to :source_account, class_name: "Account"
  # Broadcast changes in realtime with Hotwire
  after_create_commit -> { broadcast_prepend_later_to :account_ratings, partial: "account_ratings/index", locals: {account_rating: self} }
  after_update_commit -> { broadcast_replace_later_to self }
  after_destroy_commit -> { broadcast_remove_to :account_ratings, target: dom_id(self, :index) }

  after_create do
    rating_detail = AccountRatingDetail.find_or_create_by(account_id: target_account_id)
    rating_detail.increment!(:total_ratings)
    rating_detail.increment!(rating)
    rating_detail.save!
  end
end

app/controllers/account_ratings_controller.rb
class AccountRatingsController < ApplicationController
  before_action :set_account_rating, only: [:show, :edit, :update, :destroy]

  # Uncomment to enforce Pundit authorization
  # after_action :verify_authorized
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # GET /account_ratings
  def index
    @pagy, @account_ratings = pagy(AccountRating.sort_by_params(params[:sort], sort_direction))

    # Uncomment to authorize with Pundit
    # authorize @account_ratings
  end

  # GET /account_ratings/1 or /account_ratings/1.json
  def show
  end

  # GET /account_ratings/new
  def new
    @account_rating = AccountRating.new

    # Uncomment to authorize with Pundit
    # authorize @account_rating
  end

  # GET /account_ratings/1/edit
  def edit
  end

  # POST /account_ratings or /account_ratings.json
  def create
    @account_rating = AccountRating.new(account_rating_params)

    # Uncomment to authorize with Pundit
    # authorize @account_rating

    respond_to do |format|
      if @account_rating.save
        format.html { redirect_to @account_rating, notice: "Account rating was successfully created." }
        format.json { render :show, status: :created, location: @account_rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_ratings/1 or /account_ratings/1.json
  def update
    respond_to do |format|
      if @account_rating.update(account_rating_params)
        format.html { redirect_to @account_rating, notice: "Account rating was successfully updated." }
        format.json { render :show, status: :ok, location: @account_rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_ratings/1 or /account_ratings/1.json
  def destroy
    @account_rating.destroy
    respond_to do |format|
      format.html { redirect_to account_ratings_url, status: :see_other, notice: "Account rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account_rating
    @account_rating = AccountRating.find(params[:id])

    # Uncomment to authorize with Pundit
    # authorize @account_rating
  rescue ActiveRecord::RecordNotFound
    redirect_to account_ratings_path
  end

  # Only allow a list of trusted parameters through.
  def account_rating_params
    params.require(:account_rating).permit(:target_account_id, :source_account_id, :title, :review, :rating)

    # Uncomment to use Pundit permitted attributes
    # params.require(:account_rating).permit(policy(@account_rating).permitted_attributes)
  end
end

app/helpers/account_ratings_helper.rb
module AccountRatingsHelper
end

app/views/account_ratings/_account_rating.html.erb
<div id="<%= dom_id account_rating %>">
  <div class="mb-4">
    <p class="text-sm font-medium text-gray-500">Target account</p>
    <%= account_rating.target_account_id %>
  </div>
  <div class="mb-4">
    <p class="text-sm font-medium text-gray-500">Source account</p>
    <%= account_rating.source_account_id %>
  </div>
  <div class="mb-4">
    <p class="text-sm font-medium text-gray-500">Title</p>
    <%= account_rating.title %>
  </div>
  <div class="mb-4">
    <p class="text-sm font-medium text-gray-500">Review</p>
    <%= account_rating.review %>
  </div>
  <div class="mb-4">
    <p class="text-sm font-medium text-gray-500">Rating</p>
    <%= account_rating.rating %>
  </div>
</div>

app/views/account_ratings/_form.html.erb
<%= form_with(model: account_rating) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :target_account_id %>
    <%= form.text_field :target_account_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :source_account_id %>
    <%= form.text_field :source_account_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :review %>
    <%= form.text_area :review, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div>

  <div>
    <%= form.button button_text(form.send(:submit_default_value)), class: "btn btn-primary" %>

    <% if form.object.new_record? %>
      <%= link_to t("cancel"), account_ratings_path, class: "btn btn-white" %>
    <% else %>
      <%= link_to t("cancel"), account_rating_path(@account_rating), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/account_ratings/_index.html.erb
<div id="<%= dom_id(account_rating, :index) %>">
  <%= turbo_stream_from account_rating %>
  <%= render account_rating %>
  <%= link_to "View", account_rating, class: "btn btn-white" %>
</div>

app/views/account_ratings/edit.html.erb
<%= content_for :title, t("shared.scaffold.edit.title", model: "Account Rating") %>

<div class="container mx-auto px-4 my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Account Ratings", account_ratings_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.edit.title", model: "Account Rating") %>
    </h1>
    <%= button_to t("delete"), @account_rating, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: t("are_you_sure") } } %>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render "form", account_rating: @account_rating %>
  </div>
</div>

app/views/account_ratings/index.html.erb
<%= content_for :title, "Account Ratings" %>
<%= turbo_stream_from :account_ratings %>

<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <div>
      <h1 class="h3">Account Ratings</h1>

      <div class="text-sm font-medium">
        <span class="text-gray-500">Sort by:</span>
        <%= sortable @account_ratings, :target_account_id, "Target account", class: "text-gray-700 mr-1" %>
        <%= sortable @account_ratings, :source_account_id, "Source account", class: "text-gray-700 mr-1" %>
        <%= sortable @account_ratings, :title, "Title", class: "text-gray-700 mr-1" %>
        <%= sortable @account_ratings, :review, "Review", class: "text-gray-700 mr-1" %>
        <%= sortable @account_ratings, :rating, "Rating", class: "text-gray-700 mr-1" %>
      </div>
    </div>

    <%= link_to t("shared.scaffold.new.title", model: "Account Rating"), new_account_rating_path, class: "btn btn-white" %>
  </div>

  <%= tag.div id: ("account_ratings" if first_page?), class: "bg-white rounded-md shadow p-6 space-y-8" do %>
    <%= render partial: "account_ratings/index", collection: @account_ratings, as: :account_rating, cached: true %>

    <div class="hidden only:flex flex-col items-center justify-between lg:flex-row">
      <%= image_tag "empty.svg", class: "mb-4 lg:w-1/2" %>
      <div class="flex-1 text-center">
        <p class="mb-4 h3">Create your first Account Rating</p>
        <%= link_to t("shared.scaffold.new.title", model: "Account Rating"), new_account_rating_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <% if @pagy.pages > 1 %>
    <div class="my-6 text-center">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/account_ratings/new.html.erb
<%= content_for :title, t("shared.scaffold.new.title", model: "Account Rating") %>

<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Account Ratings", account_ratings_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.new.title", model: "Account Rating") %>
    </h1>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render "form", account_rating: @account_rating %>
  </div>
</div>

app/views/account_ratings/show.html.erb
<%= content_for :title, "Account Ratings ##{@account_rating.id}" %>
<%= turbo_stream_from @account_rating %>

<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Account Ratings", account_ratings_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      Account Rating #<%= @account_rating.id %>
    </h1>
    <%= link_to t("edit"), edit_account_rating_path(@account_rating), class: "btn btn-white" %>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render @account_rating %>
  </div>
</div>