config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.local?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      resources :connected_accounts
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: ("users/omniauth_callbacks" if defined? OmniAuth),
      registrations: "users/registrations",
      sessions: "users/sessions"
    }.compact
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get "session/otp", to: "sessions#otp"
  end
  resources :after_signup

  resources :announcements, only: [:index, :show]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
      delete :delete_photo_attachment
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts do
      member do
        post :resend
      end
    end
  end
  resources :account_invitations

  # Payments
  resource :billing_address
  namespace :payment_methods do
    resource :stripe, controller: :stripe, only: [:show]
  end
  resources :payment_methods
  namespace :subscriptions do
    resource :billing_address
    namespace :stripe do
      resource :trial, only: [:show]
    end
  end
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    resource :upcoming, module: :subscriptions

    collection do
      patch :billing_settings
    end

    scope module: :subscriptions do
      resource :stripe, controller: :stripe, only: [:show]
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  resources :agreements, module: :users
  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :careers
    get :guides
    get :terms
    get :privacy
    get :pricing
    get :sign_up_entry
    get :guide_onboarding
    get :become_a_guide
    post "add_email_contact", to: "add_email_contact"
    post "add_email_guide", to: "add_email_guide"
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
    resources :account_ratings
    get "/map_pins", to: "dashboard#map_pins"
    get "/page_list", to: "dashboard#page_list"
    resources :tours do
      member do
        delete :delete_photo_attachment
      end
    end
    resources :scheduled_tours do
      collection do
        get :availability
      end
    end
    get "/guide_tours/:account_id", to: "tours#guide_tours", as: "guide_tours"
    get "/success", to: "scheduled_tours#stripe_success"
    get "/cancel", to: "scheduled_tours#stripe_cancel"
    get "/scheduled_tour_payment", to: "scheduled_tours#scheduled_tour_payment"
    get "public_profile/:account_id", to: "accounts#public_profile", as: "public_profile"
  end

  resources :schedules

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/admin/pay/subscriptions_controller.rb
module Admin
  class Pay::SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Pay::Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pay::Subscription.find_by!(slug: param)
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions/billing_addresses_controller.rb
class Subscriptions::BillingAddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_plan

  layout "checkout"

  def show
  end

  def update
    @billing_address = current_account.billing_address || current_account.build_billing_address
    if @billing_address.update(billing_address_params)
      redirect_to new_subscription_path(plan: @plan, promo_code: params[:promo_code])
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_plan
    @plan = Plan.without_free.find_by_prefix_id!(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to pricing_path
  end

  def billing_address_params
    params.require(:address).permit(:line1, :line2, :city, :state, :country, :postal_code)
  end
end

app/controllers/subscriptions/cancels_controller.rb
class Subscriptions::CancelsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_subscription

  def show
  end

  def destroy
    # Metered subscriptions should end immediately so they don't rack up more charges
    if @subscription.metered?
      @subscription.cancel_now!(invoice_now: true)

    # Unpaid subscriptions are treated as canceled, so end them immediately
    elsif @subscription.unpaid? || @subscription.past_due?
      @subscription.cancel_now!

    else
      # Cancel at period end
      @subscription.cancel
    end

    redirect_to subscriptions_path, status: :see_other
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id!(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/pauses_controller.rb
class Subscriptions::PausesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_subscription

  def show
  end

  def update
    @subscription.pause
    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id!(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/resumes_controller.rb
class Subscriptions::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_subscription

  def show
  end

  def update
    @subscription.resume
    redirect_to subscriptions_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id!(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/stripe/trials_controller.rb
class Subscriptions::Stripe::TrialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan

  def show
    current_account.set_payment_processor :stripe

    # Mark setup intent payment method as default
    pay_payment_method = Pay::Stripe::PaymentMethod.sync_setup_intent(params[:setup_intent])
    pay_payment_method.make_default!

    @pay_subscription = current_account.payment_processor.subscribe(
      plan: @plan.id_for_processor(:stripe),
      trial_period_days: @plan.trial_period_days,
      automatic_tax: {
        enabled: @plan.taxed?
      },
      promotion_code: params[:promo_code]
    )
    redirect_to root_path, notice: t("subscriptions.created")
  end

  private

  def set_plan
    @plan = Plan.without_free.find_by_prefix_id!(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/stripe_controller.rb
class Subscriptions::StripeController < ApplicationController
  # Handles Stripe PaymentElement callback

  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_subscription, only: [:show]

  def show
    @subscription = Pay::Stripe::Subscription.sync(@subscription.processor_id)
    current_account.set_payment_processor :stripe

    # Mark payment intent payment method as default
    pay_payment_method = Pay::Stripe::PaymentMethod.sync_payment_intent(params[:payment_intent])
    pay_payment_method.make_default!

    if @subscription.active?
      redirect_to root_path, notice: t("subscriptions.created")
    else
      redirect_to root_path, alert: t("something_went_wrong")
    end
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id!(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions/upcomings_controller.rb
class Subscriptions::UpcomingsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_subscription

  def show
    @invoice = @subscription.upcoming_invoice
  end

  private

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id!(params[:subscription_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to subscriptions_path
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :require_payments_enabled
  before_action :authenticate_user_with_sign_up!
  before_action :require_account
  before_action :require_current_account_admin, except: [:show]
  before_action :set_plan, only: [:new, :payment, :create, :update]
  before_action :set_subscription, only: [:show, :edit, :update]
  before_action :redirect_if_already_subscribed, only: [:new]
  before_action :redirect_to_billing_address, only: [:new]
  before_action :handle_past_due_or_unpaid, only: [:new]

  layout "checkout", only: [:new, :payment, :create]

  def index
    @billing_address = current_account.billing_address
    @payment_processor = current_account.payment_processor
    @subscriptions = current_account.subscriptions.active.or(current_account.subscriptions.past_due).or(current_account.subscriptions.unpaid).order(created_at: :asc).includes([:customer])
  end

  def show
    redirect_to edit_subscription_path(@subscription)
  end

  # Stripe subscriptions are handled entirely client side
  # We need to create a subscription to render the PaymentElement
  def new
    if Jumpstart.config.stripe?
      payment_processor = current_account.add_payment_processor(:stripe)
      if @plan.trial_period_days?
        @client_secret = payment_processor.create_setup_intent.client_secret
      else
        args = {
          plan: @plan.id_for_processor(:stripe),
          trial_period_days: @plan.trial_period_days,
          payment_behavior: :default_incomplete,
          automatic_tax: {
            enabled: @plan.taxed?
          },
          promotion_code: params[:promo_code]
        }
        args[:quantity] = current_account.per_unit_quantity if @plan.charge_per_unit?
        @pay_subscription = payment_processor.subscribe(**args)
        @stripe_invoice = @pay_subscription.subscription.latest_invoice
        @client_secret = @pay_subscription.client_secret
      end
    end
  rescue Pay::Stripe::Error => e
    flash[:alert] = e.message
    redirect_to pricing_path
  end

  # Only used by Braintree
  def create
    payment_processor = params[:processor] ? current_account.set_payment_processor(params[:processor]) : current_account.payment_processor
    payment_processor.payment_method_token = params[:payment_method_token]
    args = {
      plan: @plan.id_for_processor(payment_processor.processor),
      trial_period_days: @plan.trial_period_days
    }
    args[:quantity] = current_account.per_unit_quantity if @plan.charge_per_unit?
    payment_processor.subscribe(**args)
    redirect_to root_path, notice: t(".created")
  rescue Pay::ActionRequired => e
    redirect_to pay.payment_path(e.payment.id)
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :new, status: :unprocessable_entity
  end

  def edit
    # Include current plan even if hidden
    @current_plan = @subscription.plan

    plans = Plan.visible.sorted.or(Plan.where(id: @current_plan.id))
    @monthly_plans = plans.select(&:monthly?)
    @yearly_plans = plans.select(&:yearly?)
  end

  def update
    @subscription.swap @plan.id_for_processor(current_account.payment_processor.processor)
    redirect_to subscriptions_path, notice: t(".success")
  rescue Pay::ActionRequired => e
    redirect_to pay.payment_path(e.payment.id)
  rescue Pay::Error => e
    edit # Reload plans
    flash[:alert] = e.message
    render :edit, status: :unprocessable_entity
  end

  def billing_settings
    current_account.update(billing_params)
    redirect_to subscriptions_path, notice: t(".billing_settings_updated")
  end

  private

  def billing_params
    params.require(:account).permit(:extra_billing_info, :billing_email)
  end

  def require_payments_enabled
    return if Jumpstart.config.payments_enabled?
    flash[:alert] = "Jumpstart must be configured for payments before you can manage subscriptions."
    redirect_back(fallback_location: root_path)
  end

  def set_plan
    @plan = Plan.without_free.find_by_prefix_id!(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to pricing_path
  end

  def set_subscription
    @subscription = current_account.subscriptions.find_by_prefix_id(params[:id])
    redirect_to subscriptions_path if @subscription.nil?
  end

  def redirect_if_already_subscribed
    if current_account.payment_processor&.subscribed?
      redirect_to subscriptions_path, alert: t(".already_subscribed")
    end
  end

  def redirect_to_billing_address
    if Jumpstart.config.collect_billing_address? && current_account.billing_address.nil?
      redirect_to subscriptions_billing_address_path(plan: params[:plan], promo_code: params[:promo_code])
    end
  end

  def handle_past_due_or_unpaid
    if (subscription = current_account.payment_processor&.subscription) && (subscription.past_due? || subscription.unpaid?)
      redirect_to new_payment_method_path
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def braintree_env
    Rails.env.production? ? "production" : "sandbox"
  end

  def pricing_cta(plan)
    if plan.trial_period_days?
      t(".start_trial")
    else
      t(".get_started")
    end
  end

  def payment_method_details(object)
    case object.payment_method_type
    when "paypal"
      object.email || "PayPal"
    when "card"
      "#{object.brand.titleize} ending in #{object.last4}"
    end
  end

  def show_payment_processor?(processor_name, plan: nil)
    return unless Jumpstart.config.payment_processors.include?(processor_name)

    # Make sure we have a Plan ID for the payment processor
    return false if plan && !plan.id_for_processor(processor_name).present?

    # If a user has active subscriptions, only let them use that payment processor for new payments
    # Also show if user is on the fake processor (for trial)
    if current_account.subscriptions.active.any? && current_account.payment_processor
      ["fake_processor", processor_name.to_s].include?(current_account.payment_processor.processor)

    # Otherwise show all options
    else
      true
    end
  end

  # Paddle can only update payment method when subscribed
  # Only works with active or paused subscriptions.
  # Cancelled subscriptions are permanent and cannot be updated.
  def show_paddle_payment_method_form?(payment_processor)
    return false unless payment_processor&.paddle?
    (subscription = payment_processor.subscription) && (subscription.active? || subscription.paused?)
  end
end

app/views/subscriptions/_billing_address.html.erb
<h5 id="billing-address" class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".billing_address") %></h5>

<div class="mb-8 lg:flex lg:gap-8">
  <div class="flex-1 my-4">
    <% if billing_address %>
      <div class="text-gray-700">
        <%= render billing_address %>
      </div>
    <% else %>
      <p class="text-gray-700">
        <%= t(".no_billing_address") %>
      </p>
    <% end %>
  </div>

  <div>
    <% if billing_address %>
      <%= link_to t(".update_billing_address"), edit_billing_address_path, class: "btn btn-light-gray" %>
    <% else %>
      <%= link_to t(".add_billing_address"), new_billing_address_path, class: "btn btn-light-gray" %>
    <% end %>
  </div>
</div>

app/views/subscriptions/_billing_email.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".billing_email") %></h5>

<div class="mb-8 flex gap-8 dark:text-gray-200">
  <%= form_with model: current_account, url: billing_settings_subscriptions_path do |f| %>
    <div class="flex-1">
      <div class="text-gray-700 mt-2"><%= t ".description" %></div>

      <div class="form-group mt-4 flex items-center gap-2">
        <%= f.email_field :billing_email, class: "form-control mt-0", placeholder: true %>
        <%= f.button t(".save"), class: "btn btn-primary", data: { disable_with: disable_with(t(".saving"))} %>
      </div>
    </div>
  <% end %>
</div>

app/views/subscriptions/_billing_info.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".extra_billing_info") %></h5>

<div class="mb-8 flex gap-8" data-controller="toggle">
  <div class="flex-1">
    <div class="text-gray-700 mt-2"><%= t ".additional_information" %></div>

    <%= form_with model: current_account, url: billing_settings_subscriptions_path, html: { class: "hidden mt-4 max-w-lg", data: {
                                                                                                                            toggle_target: 'toggleable',
                                                                                                                            transition_enter: 'transition-all ease-linear duration-300',
                                                                                                                            transition_enter_from: 'opacity-0 h-0',
                                                                                                                            transition_enter_to: 'opacity-100',
                                                                                                                            transition_leave: 'transition-all ease-linear duration-300',
                                                                                                                            transition_leave_from: 'opacity-100',
                                                                                                                            transition_leave_to: 'opacity-0'
                                                                                                                          }} do |f| %>
      <div class="form-group">
        <%= f.label :extra_billing_info %>
        <%= f.text_area :extra_billing_info, class: "form-control", placeholder: true %>
      </div>

      <div class="form-group">
        <%= f.button t(".save_info"), class: "btn btn-primary", data: { disable_with: disable_with(t(".saving"))} %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to t(".add_info"), "#", class: "btn btn-light-gray", data: { action: "click->toggle#toggle:prevent touch->toggle#toggle:prevent" } %>
  </div>
</div>

<% if current_account.extra_billing_info? %>
  <blockquote class="mt-4 mb-8 text-gray-600 border-l-4 border-gray-200 px-4 font-mono text-sm">
    <%= current_account.extra_billing_info %>
  </blockquote>
<% end %>

app/views/subscriptions/_charges.html.erb
<h5 class="text-gray-700 font-semibold my-4 border-b border-gray-200 pb-2"><%= t(".title") %></h5>

<% if current_account.charges.sorted.any? %>
  <table class="w-full text-sm">
    <thead class="bg-gray-100">
      <tr>
        <th class="p-3 uppercase text-left text-xs text-gray-500"><%= t ".date" %></th>
        <th class="hidden table-cell p-3 uppercase text-left text-xs text-gray-500"><%= t ".payment_method" %></th>
        <th class="p-3 uppercase text-left text-xs text-gray-500"><%= t ".amount" %></th>
        <th class="p-3 uppercase text-center text-xs text-gray-500"><%= t ".receipt" %></th>
      </tr>
    </thead>

    <tbody>
      <% current_account.charges.sorted.each do |charge| %>
        <tr class="group border-t border-gray-200 hover:bg-gray-50">
          <td class="p-3 font-medium">
            <%= link_to invoice_charge_path(charge, format: :pdf), target: :_blank do %>
              <%= charge.created_at.strftime("%B %e, %Y") %>
              <svg xmlns="http://www.w3.org/2000/svg" class="inline-block h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z" />
                <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z" />
              </svg>
            <% end %>
          </td>
          <td class="hidden table-cell p-3">
            <i class="fab fa-cc-<%= charge.brand.downcase %> text-gray-700"></i>
            <%= payment_method_details(charge) %>
          </td>
          <td class="p-3"><%= charge.amount_with_currency %></td>
          <td class="p-3 text-center text-sm">
            <% if charge.paddle_receipt_url %>
              <%= link_to t(".view"), charge.paddle_receipt_url, target: :_blank %>
            <% else %>
              <%= link_to charge_path(charge, format: :pdf), target: :_blank do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="inline-block text-gray-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="text-gray-700"><%= t(".empty") %></div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<%= tag.div class: "mb-8 lg:flex lg:gap-8", id: dom_id(subscription) do %>
  <% if subscription.generic_trial? %>
    <div>
      <%= badge t(".free_trial"), class: "mb-1" %>
      <div><%= t(".free_trial_ends", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
    </div>

  <% else %>
    <div class="flex-1">
      <% if subscription.canceled? %>
        <%= badge t(".canceled"), class: "mb-1" %>
      <% elsif subscription.incomplete? %>
        <%= badge t(".incomplete"), class: "mb-1" %>
      <% elsif subscription.past_due? %>
        <%= badge t(".past_due"), class: "mb-1", color: "bg-red-100 text-red-800" %>
      <% elsif subscription.unpaid? %>
        <%= badge t(".unpaid"), class: "mb-1", color: "bg-red-100 text-red-800" %>
      <% end %>

      <%= render partial: "subscriptions/summary", locals: { subscription: subscription } %>

      <% if subscription.metered? %>
        <div><%= link_to t(".view_usage"), subscription_upcoming_path(subscription), class: "text-sm font-medium" %></div>
      <% elsif subscription.plan&.charge_per_unit? %>
        <div><%= link_to t(".view_upcoming_invoice"), subscription_upcoming_path(subscription), class: "text-sm font-medium" %></div>
      <% end %>

      <% if subscription.on_trial? && subscription.canceled? %>
        <div><%= t(".canceled_on_trial", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
      <% elsif subscription.on_trial? %>
        <div><%= t(".trial", date: l(subscription.trial_ends_at.to_date, format: :long)) %></div>
      <% elsif subscription.on_grace_period? %>
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="inline-block fill-current text-gray-400 h-4 w-4 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
          </svg>
          <% if subscription.ends_at? %>
            <%= t(".ends_at", date: l(subscription.ends_at.to_date, format: :long)) %>
          <% elsif subscription.pause_starts_at %>
            <%= t(".paused_at", date: l(subscription.pause_starts_at.to_date, format: :long)) %>
          <% end %>
        </div>
      <% elsif subscription.paused? %>
        <div><%= t(".paused") %></div>
      <% end %>
    </div>

    <div class="mt-2 flex flex-col gap-2 text-center">
      <% if subscription.on_grace_period? && !subscription.paddle? %>
        <%# Cancelled paddle subscriptions cannot be resumed %>
        <%= link_to t(".resume"), subscription_resume_path(subscription), class: "btn btn-primary" %>
      <% elsif subscription.paused? %>
        <%= link_to t(".resume"), subscription_resume_path(subscription), class: "btn btn-primary" %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% elsif subscription.active? %>
        <%= link_to t(".change_plan"), edit_subscription_path(subscription), class: "btn btn-primary" %>
        <%= link_to t(".pause"), subscription_pause_path(subscription), class: "btn btn-light-gray" if subscription.paddle? || subscription.fake_processor? %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% elsif subscription.incomplete? %>
        <%= link_to t(".confirm_payment"), pay.payment_path(subscription.latest_payment.id), class: "btn btn-primary" %>
      <% elsif subscription.past_due? %>
        <%= link_to t(".update_payment_method"), new_payment_method_path, class: "btn btn-primary" %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% elsif subscription.unpaid? %>
        <%= link_to t(".update_payment_method"), new_payment_method_path, class: "btn btn-primary" %>
        <%= link_to t(".cancel_plan"), subscription_cancel_path(subscription), class: "btn btn-light-gray" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/subscriptions/_summary.html.erb
<h4><%= subscription.plan&.name || subscription.name %></h4>
<% unless subscription.plan.nil? %>
  <div class="mb-2 text-lg">
    <%= subscription.amount_with_currency %> / <%= subscription.plan.interval %>
  </div>
  <% if subscription.quantity > 1 || subscription.plan.charge_per_unit? %>
    <div><%= t(".quantity", quantity: subscription.quantity, price: subscription.plan.amount_with_currency, unit: (subscription.plan.unit_label? ? t(".per_unit", unit: subscription.plan.unit_label) : t(".each"))) %></div>
  <% end %>
<% end %>