config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.local?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      resources :connected_accounts
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: ("users/omniauth_callbacks" if defined? OmniAuth),
      registrations: "users/registrations",
      sessions: "users/sessions"
    }.compact
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get "session/otp", to: "sessions#otp"
  end
  resources :after_signup

  resources :announcements, only: [:index, :show]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
      delete :delete_photo_attachment
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts do
      member do
        post :resend
      end
    end
  end
  resources :account_invitations

  # Payments
  resource :billing_address
  namespace :payment_methods do
    resource :stripe, controller: :stripe, only: [:show]
  end
  resources :payment_methods
  namespace :subscriptions do
    resource :billing_address
    namespace :stripe do
      resource :trial, only: [:show]
    end
  end
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    resource :upcoming, module: :subscriptions

    collection do
      patch :billing_settings
    end

    scope module: :subscriptions do
      resource :stripe, controller: :stripe, only: [:show]
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  resources :agreements, module: :users
  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :careers
    get :guides
    get :terms
    get :privacy
    get :pricing
    get :sign_up_entry
    get :guide_onboarding
    get :become_a_guide
    post "add_email_contact", to: "add_email_contact"
    post "add_email_guide", to: "add_email_guide"
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
    resources :account_ratings
    get "/map_pins", to: "dashboard#map_pins"
    get "/page_list", to: "dashboard#page_list"
    resources :tours do
      member do
        delete :delete_photo_attachment
      end
    end
    resources :scheduled_tours do
      collection do
        get :availability
      end
    end
    get "/guide_tours/:account_id", to: "tours#guide_tours", as: "guide_tours"
    get "/success", to: "scheduled_tours#stripe_success"
    get "/cancel", to: "scheduled_tours#stripe_cancel"
    get "/scheduled_tour_payment", to: "scheduled_tours#scheduled_tour_payment"
    get "public_profile/:account_id", to: "accounts#public_profile", as: "public_profile"
  end

  resources :schedules

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Public marketing homepage
  root to: "static#index"
end

app/models/scheduled_tour.rb
# == Schema Information
#
# Table name: scheduled_tours
#
#  id                :bigint           not null, primary key
#  location          :string
#  paid              :boolean
#  phone             :bigint
#  scheduled_date    :date
#  scheduled_time    :time
#  total_paid        :decimal(8, 2)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  account_user_id   :bigint
#  assigned_guide_id :integer
#  tour_id           :bigint           not null
#
# Indexes
#
#  index_scheduled_tours_on_account_user_id  (account_user_id)
#  index_scheduled_tours_on_tour_id          (tour_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_user_id => account_users.id)
#  fk_rails_...  (assigned_guide_id => account_users.id)
#  fk_rails_...  (tour_id => tours.id)
#
class ScheduledTour < ApplicationRecord
  belongs_to :tour
  belongs_to :account_user
  belongs_to :assigned_guide, class_name: "AccountUser", optional: true
  belongs_to :tour_owner, class_name: "Account", optional: true

  validates :scheduled_date, :scheduled_time, :location, :presence => true
  validates :phone, presence: true,
    :numericality => true,
    length: {minimum: 10, maximum: 15}

  # Broadcast changes in realtime with Hotwire
  after_create_commit -> { broadcast_prepend_later_to :scheduled_tours, partial: "scheduled_tours/index", locals: {scheduled_tour: self} }
  after_update_commit -> { broadcast_replace_later_to self }
  after_destroy_commit -> { broadcast_remove_to :scheduled_tours, target: dom_id(self, :index) }

  def phone=(value)
    value.gsub!(/\D/, "") if value.is_a?(String)
    write_attribute(:phone, value.to_i)
  end
end

app/controllers/scheduled_tours_controller.rb
class ScheduledToursController < ApplicationController
  before_action :set_scheduled_tour, only: [:show, :edit, :update, :destroy]
  before_action :only_authorized, only: [:show, :edit, :update, :destroy]

  # Uncomment to enforce Pundit authorization
  # after_action :verify_authorized
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # GET /scheduled_tours
  def index
    @pagy, @scheduled_tours = pagy(ScheduledTour.where(account_user_id: current_account_user.id).sort_by_params(params[:sort], sort_direction))

    # Uncomment to authorize with Pundit
    # authorize @scheduled_tours
  end

  # GET /scheduled_tours/1 or /scheduled_tours/1.json
  def show
  end

  # GET /scheduled_tours/new
  def new
    if params[:tour_id]
      @tour = Tour.find_by_id(params[:tour_id])
      @scheduled_tour = ScheduledTour.new
      @scheduled_tour.tour = @tour
    else
      redirect_to root_path
      flash[:notice] = "You must select a tour to schedule a tour."
    end
    # Uncomment to authorize with Pundit
    # authorize @scheduled_tour
  end

  # GET /scheduled_tours/1/edit
  def edit
    @tour = @scheduled_tour.tour
  end

  # POST /scheduled_tours or /scheduled_tours.json
  def create
    @scheduled_tour = ScheduledTour.new(scheduled_tour_params)
    # Uncomment to authorize with Pundit
    # authorize @scheduled_tour

    respond_to do |format|
      if @scheduled_tour.save
        format.html do
          logo_img = "https://www.trekkwire.com/assets/Trekkwire-c73296d968061a6af217e717fc97651eed296354a8deabd05599d9a6a8257c80.png"
          image_url = @scheduled_tour.tour.account.avatar.attached? ? @scheduled_tour.tour.account.avatar.url : logo_img
          session = Stripe::Checkout::Session.create({
            payment_method_types: ["card", "cashapp"],
            line_items: [{
              price_data: {
                currency: "usd",
                product_data: {
                  name: @scheduled_tour.tour.title,
                  images: [image_url],
                  metadata: {
                    tour_id: @scheduled_tour.tour.id,
                    scheduled_tour_id: @scheduled_tour.id,
                    vendor_id: @scheduled_tour.tour.account.id,
                    vendor_name: @scheduled_tour.tour.account.name,
                    vendor_email: @scheduled_tour.tour.account.owner.email,
                    vendor_phone: @scheduled_tour.tour.account.owner.phone
                  }
                },
                tax_behavior: "inclusive",
                unit_amount: (@scheduled_tour.tour.price * 100).to_i
              },
              quantity: 1
            }],
            mode: "payment",
            success_url: success_url + "?scheduled_tour_id=" + @scheduled_tour.id.to_s + "&session_id={CHECKOUT_SESSION_ID}",
            cancel_url: cancel_url + "?scheduled_tour_id=" + @scheduled_tour.id.to_s,
            automatic_tax: {enabled: true},
            customer_email: current_user.email
          })
          redirect_to session.url, allow_other_host: true, notice: "Scheduled tour was successfully created."
        end
        format.json { render :show, status: :created, location: @scheduled_tour }
      else
        @tour = Tour.find_by_id(params[:tour_id])
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scheduled_tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_tours/1 or /scheduled_tours/1.json
  def update
    @tour = @scheduled_tour.tour
    respond_to do |format|
      if @scheduled_tour.update(scheduled_tour_params)
        format.html { redirect_to @scheduled_tour, notice: "Scheduled tour was successfully updated." }
        format.json { render :show, status: :ok, location: @scheduled_tour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scheduled_tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_tours/1 or /scheduled_tours/1.json
  def destroy
    @scheduled_tour.destroy
    respond_to do |format|
      format.html do
        redirect_to scheduled_tours_url, status: :see_other, notice: "Scheduled tour was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def stripe_success
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @scheduled_tour = ScheduledTour.find(params[:scheduled_tour_id])
    ScheduledTourNotification.with(account: @scheduled_tour.tour.account, user: current_user,
      scheduled_tour: @scheduled_tour).deliver_later(@scheduled_tour.tour.account.users.all)
    @scheduled_tour.update(paid: true, assigned_guide_id: @scheduled_tour.tour.account.users.first.id, total_paid: session["amount_total"] / 100.0)
  end

  def stripe_cancel
    @scheduled_tour = ScheduledTour.find(params[:scheduled_tour_id])
    @scheduled_tour.update(paid: false)
  end

  def availability
    @target = params[:target]
    @tour = Tour.find(params[:tour_id])
    @availability = @tour.get_availability_for_date(params[:date].to_date)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_scheduled_tour
    @scheduled_tour = ScheduledTour.find(params[:id])

    # Uncomment to authorize with Pundit
    # authorize @scheduled_tour
  rescue ActiveRecord::RecordNotFound
    redirect_to scheduled_tours_url
  end

  def only_authorized
    redirect_to root_path, notice: "Not Authorized to View Page" unless current_account_user.id == @scheduled_tour.account_user_id || current_account == @scheduled_tour.tour.account
  end

  # Only allow a list of trusted parameters through.
  def scheduled_tour_params
    scheduled_tour = params.require(:scheduled_tour).permit(:scheduled_date, :scheduled_time, :phone, :location, :tour_id,
      :account_user_id, :assigned_guide_id)
    unless params[:tour_id].blank?
      scheduled_tour[:tour_id] = params[:tour_id]
    end
    unless params[:account_user_id].blank?
      scheduled_tour[:account_user_id] = params[:account_user_id]
    end
    scheduled_tour
    # Uncomment to use Pundit permitted attributes
    # params.require(:scheduled_tour).permit(policy(@scheduled_tour).permitted_attributes)
  end
end

app/helpers/scheduled_tours_helper.rb
module ScheduledToursHelper
end

app/views/scheduled_tours/_carousel.html.erb
<div class="relative" data-controller="carousel">
  <div class="absolute left-0 bottom-0 top-0 flex items-center">
    <button data-action="click->carousel#previous" type="button" class="rounded-full bg-gray-300 z-50">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
      </svg>
    </button>
  </div>
  <div class="absolute right-0 bottom-0 top-0 flex items-center">
    <button data-action="click->carousel#next" type="button" class="rounded-full bg-gray-300 z-50">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
      </svg>
    </button>
  </div>
  <% @tour.photos.each_with_index do |photo, idx| %>
    <div data-carousel-target="image" class="<%= idx > 0 ? "hidden" : nil %>">
      <%=
        turbo_frame_tag "photo-#{photo.id}",
                        class: "absolute top-0 left-0 right-0 bottom-0",
                        src: photo.url,
                        loading: :lazy
      %>
      <%= image_tag photo, alt:"", class:"w-full rounded-2xl object-cover z-20"%>
    </div>
  <% end %>
</div>

app/views/scheduled_tours/_scheduled_tour.html.erb
<div class="bg-gray-50 id="<%= dom_id scheduled_tour %>">
  <div class="mx-auto max-w-2xl pt-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="space-y-2 px-4 sm:flex sm:items-baseline sm:justify-between sm:space-y-0 sm:px-0">
      <div class="flex sm:items-baseline sm:space-x-4">
        <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Scheduled Tour #<%= scheduled_tour.id %></h1>
      </div>
      <p class="text-sm text-gray-600">Order placed <time datetime=<%= scheduled_tour.created_at.strftime("%B %d, %Y")%> class="font-medium text-gray-900"><%= scheduled_tour.created_at.strftime("%B %d, %Y")%></time></p>
    </div>

    <!-- Products -->
    <div class="mt-6">
      <div class="space-y-8">
        <div class="border-b border-t border-gray-200 bg-white shadow-sm sm:rounded-lg sm:border">
          <div class="px-4 py-6 sm:px-6 lg:grid lg:grid-cols-12 lg:gap-x-8 lg:p-8">
            <div class="sm:flex lg:col-span-7">
              <div class="aspect-h-1 aspect-w-1 w-full flex-shrink-0 overflow-hidden rounded-lg sm:aspect-none sm:h-40 sm:w-40">
              <% if scheduled_tour.tour.photos.any? %>
                <%= image_tag scheduled_tour.tour.photos.first, class:"h-full w-full object-cover object-center sm:h-full sm:w-full" %>
              <% end %>
              </div>

              <div class="mt-6 sm:ml-6 sm:mt-0">
                <h3 class="text-base font-medium text-gray-900">
                  <%= link_to scheduled_tour.tour.title, public_profile_path(scheduled_tour.tour.account_id) %>
                </h3>
                <p class="mt-2 text-sm font-medium text-gray-900"><%= number_to_currency(scheduled_tour.tour.price) %></p>
                <p class="mt-3 text-sm text-gray-500"><%= scheduled_tour.tour.tagline %></p>
              </div>
            </div>

            <div class="mt-6 lg:col-span-5 lg:mt-0">
              <dl class="grid grid-cols-2 gap-x-6 text-sm">
                <div>
                  <dt class="font-medium text-gray-900">Guide Details</dt>
                  <dd class="mt-3 text-gray-500">
                    <% if scheduled_tour.assigned_guide_id %>
                      <span class="block"><%= User.find(scheduled_tour.assigned_guide_id).name %></span>
                      <span class="block"><%= number_to_phone(User.find(scheduled_tour.assigned_guide_id).phone) %></span>
                      <span class="block"><%= User.find(scheduled_tour.assigned_guide_id).email %></span>
                    <% else %>
                      Pending assignment
                    <% end %>
                  </dd>
                </div>
                <div>
                  <dt class="font-medium text-gray-900">Traveler Details</dt>
                  <dd class="mt-3 text-gray-500">
                    <% if scheduled_tour.assigned_guide_id %>
                      <span class="block"><%= scheduled_tour.account_user.user.name %></span>
                      <span class="block"><%= number_to_phone(scheduled_tour.phone) %></span>
                      <span class="block"><%= scheduled_tour.account_user.user.email %></span>
                    <% else %>
                      Pending assignment
                    <% end %>
                  </dd>
                </div>
              </dl>
            </div>
          </div>

          <div class="border-t border-gray-200 px-4 py-6 sm:px-6 lg:p-8">
            <h4 class="sr-only">Status</h4>
            <p class="text-sm font-medium text-gray-900">Scheduled for <%= scheduled_tour.scheduled_date.strftime("%A %B %d, %Y") %> at <%= scheduled_tour.scheduled_time.strftime("%H:%M %p") %></p>
            <div class="mt-6" aria-hidden="true">
              <div class="overflow-hidden rounded-full bg-gray-200">
                <% if scheduled_tour.paid == true %>
                  <div class="h-2 rounded-full bg-indigo-600" style="width: calc((1 * 2 + 1) / 8 * 100%)"></div>
                <% else %>
                  <div class="h-2 rounded-full bg-indigo-600" style="width: 0"></div>
                <% end %>
              </div>
              <div class="mt-6 hidden grid-cols-4 text-sm font-medium text-gray-600 sm:grid">
                <div class="text-indigo-600">Order placed</div>
                <div class="text-center text-indigo-600">Paid</div>
                <div class="text-center">Tour Started</div>
                <div class="text-right">Tour Complete</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Billing -->

    <%
=begin%>
 <div class="mt-16">
      <h2 class="sr-only">Billing Summary</h2>

      <div class="bg-gray-100 px-4 py-6 sm:rounded-lg sm:px-6 lg:grid lg:grid-cols-12 lg:gap-x-8 lg:px-8 lg:py-8">
        <dl class="grid grid-cols-2 gap-6 text-sm sm:grid-cols-2 md:gap-x-8 lg:col-span-7">
          <div>
            <dt class="font-medium text-gray-900">Billing address</dt>
            <dd class="mt-3 text-gray-500">
              <span class="block">Floyd Miles</span>
              <span class="block">7363 Cynthia Pass</span>
              <span class="block">Toronto, ON N3Y 4H8</span>
            </dd>
          </div>
          <div>
            <dt class="font-medium text-gray-900">Payment information</dt>
            <dd class="-ml-4 -mt-1 flex flex-wrap">
              <div class="ml-4 mt-4 flex-shrink-0">
                <svg aria-hidden="true" width="36" height="24" viewBox="0 0 36 24" class="h-6 w-auto">
                  <rect width="36" height="24" rx="4" fill="#224DBA" />
                  <path d="M10.925 15.673H8.874l-1.538-6c-.073-.276-.228-.52-.456-.635A6.575 6.575 0 005 8.403v-.231h3.304c.456 0 .798.347.855.75l.798 4.328 2.05-5.078h1.994l-3.076 7.5zm4.216 0h-1.937L14.8 8.172h1.937l-1.595 7.5zm4.101-5.422c.057-.404.399-.635.798-.635a3.54 3.54 0 011.88.346l.342-1.615A4.808 4.808 0 0020.496 8c-1.88 0-3.248 1.039-3.248 2.481 0 1.097.969 1.673 1.653 2.02.74.346 1.025.577.968.923 0 .519-.57.75-1.139.75a4.795 4.795 0 01-1.994-.462l-.342 1.616a5.48 5.48 0 002.108.404c2.108.057 3.418-.981 3.418-2.539 0-1.962-2.678-2.077-2.678-2.942zm9.457 5.422L27.16 8.172h-1.652a.858.858 0 00-.798.577l-2.848 6.924h1.994l.398-1.096h2.45l.228 1.096h1.766zm-2.905-5.482l.57 2.827h-1.596l1.026-2.827z" fill="#fff" />
                </svg>
                <p class="sr-only">Visa</p>
              </div>
              <div class="ml-4 mt-4">
                <p class="text-gray-900">Ending with 4242</p>
                <p class="text-gray-600">Expires 02 / 24</p>
              </div>
            </dd>
          </div>
        </dl>

        <dl class="mt-8 divide-y divide-gray-200 text-sm lg:col-span-5 lg:mt-0">
          <div class="flex items-center justify-between pb-4">
            <dt class="text-gray-600">Subtotal</dt>
            <dd class="font-medium text-gray-900">$72</dd>
          </div>
          <div class="flex items-center justify-between py-4">
            <dt class="text-gray-600">Shipping</dt>
            <dd class="font-medium text-gray-900">$5</dd>
          </div>
          <div class="flex items-center justify-between py-4">
            <dt class="text-gray-600">Tax</dt>
            <dd class="font-medium text-gray-900">$6.16</dd>
          </div>
          <div class="flex items-center justify-between pt-4">
            <dt class="font-medium text-gray-900">Order total</dt>
            <dd class="font-medium text-indigo-600">$83.16</dd>
          </div>
        </dl>
      </div>
    </div> 
<%
=end%>
  </div>
</div>

app/views/scheduled_tours/_scheduled_tour_row.html.erb
<div id="<%= dom_id scheduled_tour %>">
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= scheduled_tour.scheduled_date %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= scheduled_tour.scheduled_time.strftime("%H:%M %p") %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= scheduled_tour.location %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= link_to scheduled_tour.tour.title, edit_scheduled_tour_path(scheduled_tour) %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= scheduled_tour.account_user.blank? ? "Unknown user" : link_to(scheduled_tour.account_user.user.name, account_path(scheduled_tour.account_user.account)) %></td>
  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
    <%= link_to "show", scheduled_tour_path(scheduled_tour) %>
  </td>
</div>

app/views/scheduled_tours/edit.html.erb
<%= content_for :title, t("shared.scaffold.edit.title", model: "Scheduled Tour") %>
<div class="container mx-auto px-4 my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Scheduled Tours", scheduled_tours_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.edit.title", model: "Scheduled Tour") %>
    </h1>
    <%= button_to t("delete"), @scheduled_tour, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: t("are_you_sure") } } %>
  </div>
  <div class="p-8 bg-white rounded shadow">
    <%= render "form", scheduled_tour: @scheduled_tour %>
  </div>
</div>

app/views/scheduled_tours/new.html.erb
<%= content_for :title, t("shared.scaffold.new.title", model: "Scheduled Tour") %>
<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Scheduled Tours", scheduled_tours_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= t("shared.scaffold.new.title", model: "Scheduled Tour") %>
    </h1>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render "form", scheduled_tour: @scheduled_tour %>
  </div>
</div>

app/views/scheduled_tours/show.html.erb
<%= content_for :title, "Scheduled Tours ##{@scheduled_tour.id}" %>
<%= turbo_stream_from @scheduled_tour %>

<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to "Scheduled Tours", scheduled_tours_path, class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      Scheduled Tour #<%= @scheduled_tour.id %>
    </h1>
    <%= link_to t("edit"), edit_scheduled_tour_path(@scheduled_tour), class: "btn btn-white" %>
  </div>

  <div class="p-8 bg-white rounded shadow">
    <%= render @scheduled_tour %>
  </div>
</div>

app/views/scheduled_tours/stripe_cancel.html.erb
<%= content_for :title, "Scheduled Tours ##{@scheduled_tour.id}" %>
<%= turbo_stream_from @scheduled_tour %>

<turbo-frame id="guides", data-turbo-action="advance">

  <div class="container px-4 mx-auto my-8">
    <div class="flex items-center justify-between mb-4">
      <h1 class="h3">
        <%= link_to "Scheduled Tours", scheduled_tours_path, class: "text-black" %>
        <span class="text-gray-400 font-light mx-2">\</span>
        <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">PAYMENT FAILED ... </span>
      </h1>
      <%= link_to t("edit"), edit_scheduled_tour_path(@scheduled_tour), class: "btn btn-white" %>
    </div>

    <div class="p-8 bg-white rounded shadow">
      <%= render @scheduled_tour %>
    </div>
  </div>
</turbo-frame>

app/views/scheduled_tours/stripe_success.html.erb
<%= content_for :title, "Scheduled Tours ##{@scheduled_tour.id}" %>
<%= turbo_stream_from @scheduled_tour %>

<turbo-frame id="guides", data-turbo-action="advance">
  <div class="container px-4 mx-auto my-8">
    <div class="flex items-center justify-between mb-4">
      <h1 class="h3">
        <%= link_to "Scheduled Tours", scheduled_tours_path, class: "text-black" %>
        <span class="text-gray-400 font-light mx-2">\</span>
        Scheduled Tour #<%= @scheduled_tour.id %>
        <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">SUCCESSFULLY PAID!!</span>
      </h1>
      <%= link_to t("edit"), edit_scheduled_tour_path(@scheduled_tour), class: "btn btn-white" %>
    </div>

    <div class="p-8 bg-white rounded shadow">
      <%= render @scheduled_tour %>
    </div>
  </div>
</turbo-frame>